### ISSUE TITLE
Colorize pseudo-indent of wrapped lines

### ISSUE THREAD

**Issue by James-Mat** [oderwat/vscode-indent-rainbow#146] opened 2023-01-20 02:07 UTC
This is about the same as  #57.

Is this still not fixable due to API limitations?  
I read in another extension that it wasn't possible, since the coloring is achieved by applying the background to the whitespace-characters - which aren't there when a line is just wrapped and not indented.

About whether this should not be fixed: I think at least an option would be of value.  
Also, it would be in line with what vscode does natively: Looking at bracketPairColorization, the vertical line is also extended over wrapped lines. If one were to incapsulate all indents with brackets, bracketPairColorization would paint the indents exactly as is suggested here.  
Personally, I would greatly appreciate that, since I use the colored indents as a visual guide for the indent of the line, which would still be the same for wrapped parts of that line. In off-side-rule languages like Python, the indentation carries the same meaning as bracketing in free-form languages, so a continued color for wrapped lines would be consistent. The shattered look wrapped lines have now also just seems unpleasing to me.  

The only thing which would indicate an incorrect depth would be the editor.wrappingIndent setting when set to deepIndent: the wrapped lines then visually have a deeper indent, but consequently would still need to keep the color of the previous level, since the line to which they belong has an indent of that level.

**Comment by oderwat** [comment] 2023-01-20 03:16
Duplicate of #57

**Closed by oderwat** 2023-01-20 03:16 UTC
