### ISSUE TITLE
All tab indents are shown as errors

### ISSUE THREAD

**Issue by miketsts** [oderwat/vscode-indent-rainbow#52] opened 2019-03-10 09:59 UTC
I use tabs for indents in my C++ files. Recently I started seeing all such indents in error color. If I retype them as spaces, they are colored as normal. 
I tried to change the VS Code settings to define indents as spaces or not - it seems that the extension just ignores this.

**Comment by oderwat** [comment] 2019-03-10 14:28
Not sure how I can help. A quick test with the current release version of the plugin seems to work ok. Are you sure you are not mixing tabs with spaces?

![image](https://user-images.githubusercontent.com/719156/54086370-27263600-4349-11e9-88f0-544d0342209a.png)

**Comment by markl-vesper** [comment] 2019-03-10 20:59
Same issue started happening for me since VS Code updated to 1.32.1

This file had correct rainbow indents on Friday. Upgraded this morning and now I'm seeing the red on ALL lines with tabs. Its not a mixture of tabs and spaces as that correctly shows error and if I fix the mix then it returns to red line. Disabling extension removes red lines

As per @miketsts comment I can resolve by converting to spaces and the correct rainbow returns.

Snippet of issue

![image](https://user-images.githubusercontent.com/41560338/54091293-a23c2a80-43e3-11e9-8b38-e0fe44ed6f5e.png)

Snippet of when mixing space and tabs with resulting linter error (proving the issue is not spacing issue)

![image](https://user-images.githubusercontent.com/41560338/54091319-d6afe680-43e3-11e9-8113-b7abdcb609ec.png)

Snippet of correct rainbow indent when using spaces instead of tabs

![image](https://user-images.githubusercontent.com/41560338/54091382-4f16a780-43e4-11e9-963d-23b0e0d97807.png)

**Comment by oderwat** [comment] 2019-03-10 21:34
Strange, still can't reproduce it. I use it myself with 1.32.1 (on OS X) and have no such problems.

![image](https://user-images.githubusercontent.com/719156/54091706-62ddf180-4383-11e9-854d-cd4a675533ef.png)

*Linter complains about TAB.. Line 18 has an extra space.*

So it is probably system or (just) configuration dependent. My first guess is that some default has changed in 1.32.1 which I have defined and you both don't.

For reference my "non plugin" related settings:

```json
	"telemetry.enableCrashReporter": false,
	"telemetry.enableTelemetry": false,
	"editor.minimap.enabled": true,
	"editor.detectIndentation": true,
	"editor.tabSize": 2,
	"editor.scrollBeyondLastLine": false,
	"editor.wrappingIndent": "none",
	"editor.renderWhitespace": "all",
	"editor.quickSuggestionsDelay": 500,
	"editor.autoClosingBrackets": "never",
	"workbench.statusBar.visible": true,
```

**Comment by miketsts** [comment] 2019-03-10 22:18
I succeeded to reproduce with the simplest case:
![Screenshot from 2019-03-11 00-16-25](https://user-images.githubusercontent.com/33390384/54092275-0551a100-4393-11e9-818f-99f1f0b60a57.png)

If I remove the space on the second line, or entire comment - the tab indent is colored correctly

**Comment by markl-vesper** [comment] 2019-03-10 22:20
tks for quick reply

I'm on Windows 10 Pro vers 1803 OSBuild 17134.590

I've check my settings and adjusted to yours and same issue applies

**Comment by oderwat** [comment] 2019-03-10 22:30
Well I guess the editor is reading that space and "guesses" that the file has spaces as indentation, which is picked up by the plugin which then (rightfully) complains about those tabs being not correct.

Could you try

```
"editor.detectIndentation": false
```

I guess they changed what `activeEditor.options.tabSize` contains or how it works. Until now it was the tab size which the plugins converts into spaces to replace all tabs before checking if the length is evenly divisible by the tab size.

If it does not return this tab size anymore, I currently have no clue on how to fix that!

**Comment by markl-vesper** [comment] 2019-03-10 22:33
I'll try now.

I checked another project/folder and on other files its only happening on multiline comments in other projects. For some reason the other project has all the red lines so I will start checking folder specific settings

![image](https://user-images.githubusercontent.com/41560338/54092476-69a34d80-43f1-11e9-98b2-844d3767ca71.png)

**Comment by miketsts** [comment] 2019-03-10 22:39
It is false in my $HOME/.config/Code/User/settings.json :

"editor.detectIndentation": false,
"editor.tabSize": 8,
"editor.insertSpaces": false,

Any other location to check:

**Comment by oderwat** [comment] 2019-03-10 22:41
To me it looks like this:

Only tabs in the first line with whitespace in front. 

![image](https://user-images.githubusercontent.com/719156/54092519-71c9a180-438d-11e9-94a8-fa0c37305d1b.png)

But if the first line with whitespace in a tab indented file contains a space, it does not work.

![image](https://user-images.githubusercontent.com/719156/54092553-b0f7f280-438d-11e9-8af1-4c47d02d2a0f.png)

![image](https://user-images.githubusercontent.com/719156/54092531-8ad25280-438d-11e9-9e2b-afd482477493.png)

![image](https://user-images.githubusercontent.com/719156/54092564-d84ebf80-438d-11e9-823e-13267671f50d.png)

Again no problem if that happens a line later:

![image](https://user-images.githubusercontent.com/719156/54092544-9e7db900-438d-11e9-8182-c83c24c40a78.png)

So I still guess it has to do what VSC detect. The plugin does not care for "the first" line.

**Comment by markl-vesper** [comment] 2019-03-10 22:47
In my file the first indented line is a tab and it shows as red.

![image](https://user-images.githubusercontent.com/41560338/54092615-16ca9580-43f3-11e9-8478-187d1b6467a0.png)

 If I remove indent then linter fires error about indentation

![image](https://user-images.githubusercontent.com/41560338/54092630-48dbf780-43f3-11e9-8029-e04599e405ed.png)

If I add tab back in manually or via quickfix it goes back to red

![image](https://user-images.githubusercontent.com/41560338/54092639-601ae500-43f3-11e9-9951-86b25e39c254.png)

There is no spaces being mixed with tabs on any lines

**Comment by oderwat** [comment] 2019-03-10 22:52
Well as I wrote: The first line with whitespace in front contains a space.

![image](https://user-images.githubusercontent.com/719156/54092679-3def7b80-438f-11e9-88e6-9f1cd8ed7e33.png)

I bet If you add a tab as first whitespace in the file above that line like `TAB// Just a tabbed line` it will work.

**Comment by markl-vesper** [comment] 2019-03-10 22:57
Yep - I missed the multiline comment at top. My bad

Removing whitespace in multiline comment is fixing the issue and leaves red lines only around multiline comments. 

![image](https://user-images.githubusercontent.com/41560338/54092749-b89eb200-43f4-11e9-9568-94e22584a6ce.png)

I've no issue with reverting to other style of comments if this is caused by breaking changes in VS Code.

Thanks

**Comment by oderwat** [comment] 2019-03-10 23:01
OK. I am going to check what internally happens probably later anyway. It would be nice if I could still "read" what is in the status line. This is what I think it did before this (potential) bogus behaviour.

**Comment by pereirinha** [comment] 2019-03-10 23:17
Dunno if this helps, but all my PHP files are now being flagged with indents errors. These files looked ok a few days ago.

<img width="105" alt="Screenshot 2019-03-10 at 23 13 56" src="https://user-images.githubusercontent.com/2189187/54092968-51e4ae80-438a-11e9-9d8f-76ff46cd4253.png">

**Comment by markl-vesper** [comment] 2019-03-10 23:50
@pereirinha 

As per Hans and my comments its being caused by the spaces in your multiline comments. I've reverted to not using multiline comment style to remove the issue.

You will have to use // for each line of your code you wish to comment

**Comment by oderwat** [comment] 2019-03-10 23:54
@markl-vesper / @pereirinha You still can use multiline comments you just need to make sure that the first ever beginning of line whitespace starts with a TAB. For PHP the workaround could be a simple as:

```php
<?php
<TAB>// fix indentation detection
/*
 * my comment
 */
<TAB>class anything {
<TAB><TAB>public...
}

**Comment by oderwat** [comment] 2019-03-10 23:55
Besides that: Just don't use TABs ;-)

**Comment by markl-vesper** [comment] 2019-03-11 00:18
Agreed @oderwat 

My original solution was playing havoc with JSDocumentation which uses multiline comments. Have changed VSCode to insert 4 spaces and my linter to 4 spaces and now everything is playing nicely

Thanks

**Comment by pereirinha** [comment] 2019-03-11 00:39
Thanks for the feedbacks @oderwat and @markl-vesper 

The tabs/spaces war is always debatable, but in my case, it's more than a personal preference.
Tabs are part of the code standards on the industry I work.

For the time being, I'll have to disable this extension.

However, I'll keep an eye on this thread, wishing for a solution with a closer outcome from a few days ago.

**Comment by miketsts** [comment] 2019-03-11 08:07
Thanks for quick checks, guys. Similar to @pereirinha , I work in a code base developed according to conventions, and apparently can't modify all files. 

But I also like this extension very much, so I don't like the idea to disable it. I'll probably live with the current state.

If you guys think it's a latest VSC bug - can you open it for them? Both @markl-vesper and myself saw that editor.detectIndentation doesn't affect the problem.

I see in release notes, that they do fix bugs :-)

**Comment by oderwat** [comment] 2019-03-11 13:35
As the plugin was once featured on the main page, they may be interested in fixing it. But I have to check first what exactly is the cause and if there is a fix or good work around. But as mentioned in other issues the plugin is not a top priority for me esp. with >200,000 installs and zero donations. 

If somebody want's to analyse the problem and / or search for a fix I will gladly accept a PR for that.

**Comment by EthanNYT** [comment] 2019-03-12 15:39
Same issue here.

OSX 10.13.6
VSCode 1.30.2

<img width="95" alt="Screen Shot 2019-03-12 at 11 31 34 AM" src="https://user-images.githubusercontent.com/29407693/54213869-886e1680-44bb-11e9-9b06-47663fdd37a0.png">

**Comment by oderwat** [comment] 2019-03-12 16:44
@EthanNYT Sure. Will be the same for all people using this kind of setup.

**Comment by SteseDav** [comment] 2019-03-12 17:15
Updated to V 1.32.1 seems to have fixed this. I did have to go back and 'Retab' the errors, but after that, it seems fine.

![image](https://user-images.githubusercontent.com/8818293/54220985-7bb4e700-44ea-11e9-9bfe-95125a86d4ae.png)

**Comment by oderwat** [comment] 2019-03-12 17:21
@SteseDav I don't think the problem is fixed in 1.32.1 because that is when it was introduced.

I wrote down in https://github.com/oderwat/vscode-indent-rainbow/issues/52#issuecomment-471361557 how to reproduce the problem and how to work around it. Please double check your case.

**Comment by SteseDav** [comment] 2019-03-13 06:56
Can't explain that then! I'm getting the correct rainbow on my PHP code....  I've edited my post accordingly to ensure misleading information isn't spread! :)

**Comment by oderwat** [comment] 2019-03-13 08:30
@SteseDav I get the correct rainbow on all my code. Does your PHP code uses TABs and has the first line of leading whitespace using a regular space? If not: All OK... if yes: Strange, please make a screenshot or post the (beginning) of that file as code snippet.

**Comment by oderwat** [comment] 2019-03-13 13:43
OK. Good news!

You should be able to work around this problem just by defining an empty tabmixColor in the configuration:

```
"indentRainbow.tabmixColor": ""
```

I am still not sure what causes the problem but I think this will make everybody happy for now. I may also remove this and the "error" indicator from the plugin as this should be done by a linter tool anyway.

**Comment by Manc** [comment] 2019-03-15 08:03
Hi, I tried the `"indentRainbow.tabmixColor": ""` workaround, but this still highlights the first few characters of multi-line DocBlocks, which looks like errors.

Sadly I'll have to disable the plugin for now, but will keep an eye on it.

**Comment by oderwat** [comment] 2019-03-15 11:39
@Manc Of course it does, because they **are** an error by definition. If you don't want to have any of those errors shown you can simply disable this for all (or some) languages or patterns:

```
  "indentRainbow.ignoreErrorLanguages" : [
     "*"
  ]
```

**Comment by Manc** [comment] 2019-03-15 11:46
@oderwat Not sure what definition you are referring to. I'd be surprised if the single space character in front of the `*` in a DocBlock is an error – it never has been in any editor I've ever known, despite using tabs as the DocBlock format is not related to the general indentation style of the file. It only became a problem in Visual Studio Code with this plugin in recent days.

**Comment by oderwat** [comment] 2019-03-15 13:09
@Manc The definition of how this plugin works. I don't want to discuss coding styles but having spaces in front of any line is not having only tabs as indentation. This plugin was made for languages which would not accept that. Using it with another language can be configured. You just need to read the documentation.

**Comment by EthanNYT** [comment] 2019-03-15 14:34
Turns out this plugin is configured to ignore JS DocBlock comments by default:

```js
 // Skip error highlighting for RegEx patterns. 
 // Defaults to ignoring JSDoc comments with a single extra space.
  "indentRainbow.ignoreLinePatterns": [
    "/.*\\*.*/g"
  ]
```

The documentation provides a slightly different example:
```js
"indentRainbow.ignoreLinePatterns": [
    "/.*\\*.*/mg"
]
```

However, even with all of the below options set, I'm still seeing error highlights for DocBlock comments:
```js
"indentRainbow.ignoreLinePatterns": [
	"/.*\\*.*/g",
	"/.*\\*.*/mg"
],
"indentRainbow.ignoreErrorLanguages": [
	"javascript"
]
```

I think the best suggestion is to use a linter for error highlighting, and use Indent Rainbow for indent rainbows. Or provide a config option to disable error highlighting altogether.

**Comment by miltoncandelero** [comment] 2019-03-15 15:02
Settings are a suggestion 😐 
```
    "indentRainbow.ignoreLinePatterns": [
        "/.*\\*.*/g",
    ],
    "indentRainbow.ignoreErrorLanguages": [
        "*"
    ],
    "indentRainbow.errorColor": "rgba(0,0,0,0.0)"
```

So, the regex says that it should ignore lines that look like ` * `
Then, it says to never show errors.
Then it says that errors are to be colored black with alpha 0

This is the result.
![image](https://user-images.githubusercontent.com/15253010/54440688-f9126e80-4719-11e9-8330-0ffa8f7db684.png)

The regex didn't ignore it.
It is showing errors.
Errors are still red.

**Comment by oderwat** [comment] 2019-03-15 15:52
@miltoncandelero There is no

```
"indentRainbow.tabmixColor": ""
```

in your first example (which I wrote as solution some comments before).

**Comment by oderwat** [comment] 2019-03-15 15:56
And yes: I am going to remove all "error" related stuff in a 2.0.0 which I will release soon. 

Because: This is something for a linter (and configuration seems to be hard)

The plugin was meant for Nim and Python mostly which I published so that fellow co-workers could easily install it. That it gained nearly a quarter million users was rather unexpected.

**Comment by oderwat** [comment] 2019-03-15 16:03
To avoid further diversion on the topic and present a solution:
---
To work around the original issue add the following to your config:
```
"indentRainbow.tabmixColor": ""
```
#### Analysis
The problem of "wrong" highlighting of tabs arises when the first whitespace in a tab indented file contains a space.

Future version of this plugin will not do any error highlighting anymore. Take a linter for that.

**Closed by oderwat** 2019-03-15 16:03 UTC

**Comment by miketsts** [comment] 2019-03-15 16:23
> Future version of this plugin will not do any error highlighting anymore. Take a linter for that.

A pity, it was handy. But of course, it's your decision.

**Comment by oderwat** [comment] 2019-03-15 17:20
@miketsts I may just change the default config to not have it enabled and remove it from the documentation as I still use it myself. But I will definitely not do any more support for such feature.

**Comment by oderwat** [comment] 2019-03-19 03:07
I released an update of the plugin which fixes a regression which caused this problem and also has some new defaults to make people "more happy" (TM)

Please try this!
