### ISSUE TITLE
Colour empty lines between code when in scopes

### ISSUE THREAD

**Issue by nicovarley** [oderwat/vscode-indent-rainbow#171] opened 2023-12-29 13:04 UTC
Hi, I love rainbow indent - I don't think I can write code without it lol. There's one feature that I really wish it would do though, which is colouring the empty lines based on what scope the code is in. I have another rainbow indenter installed on the IDE Pycharm:
![image](https://github.com/oderwat/vscode-indent-rainbow/assets/83963295/1f2de941-f8f7-409c-a9f3-27fa022ae9a6)
It colours the empty lines to match what scope you're in, it both looks nice and makes it easier to follow where your indentation is.

![image](https://github.com/oderwat/vscode-indent-rainbow/assets/83963295/c87245ab-dc42-45c5-9641-76ffe91f8f29)
This one leaves gaps everywhere which don't look very nice, so it'd be amazing to have an option that would keep the scope's level of indentation throughout. E.g. the lime green colour would be on every line as it's in class and the dark green one would be on every line within the method. I wouldn't mind manually leaving the tabs in myself, but VSCode seems to remove them for you on empty lines and the colourless gaps reappear.

Thank you!

**Comment by oderwat** [comment] 2023-12-29 13:49
First: I do not want that. This would look like there are spaces or tabs in the line. That there is no color show me, that there is nothing and I like this.
Second: It is not possible to do this with how the plugin works. It set's the background of the content and there is not content in an empty line
Third: This is a duplicate of #7 #28 #71 #72 #137 and #166

**Closed as completed by oderwat** 2023-12-29 13:49 UTC

**Comment by soyosef** [comment] 2024-10-08 06:32
I also wanted to color empty rows. For anyone reading this thread, there is no need for extensions. A solution is to add something like the following to your settings.json and customize to your needs:

```json
"workbench.colorCustomizations": {
    "editorIndentGuide.background1": "#FFFF4080",
    "editorIndentGuide.background2": "#7FFF7F80",
    "editorIndentGuide.background3": "#FF7FFF80",
    "editorIndentGuide.background4": "#4FECEC80",
    "editorIndentGuide.background5": "#FFC0CB80",
    "editorIndentGuide.background6": "#ADD8E680",

    "editorIndentGuide.activeBackground1": "#FFFF40D0",
    "editorIndentGuide.activeBackground2": "#7FFF7FD0",
    "editorIndentGuide.activeBackground3": "#FF7FFFD0",
    "editorIndentGuide.activeBackground4": "#4FECECD0",
    "editorIndentGuide.activeBackground5": "#FFC0CBD0",
    "editorIndentGuide.activeBackground6": "#ADD8E6D0",
}

```

Result:
<img width="431" alt="image" src="https://github.com/user-attachments/assets/aa9228db-b4ca-4bc4-9b6a-62972f3525eb">

**Comment by Taxato** [comment] 2024-12-10 12:48
You're an absolute legend @soyosef
